name: ECS Fargate with Terraform

on:
  push:
    branches:
      - main
      - version-2
  workflow_dispatch:
    inputs:
      destroy:
        description: "Destroy infrastructure"
        required: true
        default: "false"

jobs:
  deploy_or_destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -o awscliv2.zip
          sudo ./aws/install --update

      - name: Configure AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-southeast-1
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_DEFAULT_REGION

      - name: Print Debug Info
        run: |
          echo "AWS Access Key: ${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS Region: ap-southeast-1"

      - name: Terraform Init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-southeast-1
        run: |
          terraform init

      - name: Terraform Plan
        env:
          SECRET_NAME: ${{ secrets.SECRET_NAME }}
        run: |
          terraform plan -out "plan.out" -var "secret_name=$SECRET_NAME"

      - name: Terraform Apply
        if: github.event.inputs.destroy != 'true'
        run: |
          terraform apply -auto-approve "plan.out"

      - name: Terraform Destroy
        if: github.event.inputs.destroy == 'true'
        env:
          SECRET_NAME: ${{ secrets.SECRET_NAME }}
        run: |
          terraform destroy -auto-approve \
            -var "secret_name=$SECRET_NAME"
